version: '3.1'

services:

  eureka:
    container_name: "eureka"
    image: trcklst/eureka:1.0.0
    environment:
      SERVER_PORT: 8761
      SPRING_PROFILE: default
    ports:
      - "8761:8761"

  subscription:
    container_name: "subscription"
    image: trcklst/subscription:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILE: docker
    ports:
      - "8082:8082"
    depends_on:
      - subscription_db
      - eureka

  authentication:
    container_name: "authentication"
    image: trcklst/authentication:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8083
      SPRING_PROFILE: docker
    ports:
      - "8083:8083"
    depends_on:
      - user_db
      - eureka

  register:
    container_name: "register"
    image: trcklst/register:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8070
      SPRING_PROFILE: docker
    ports:
      - "8070:8070"
    depends_on:
      - user_db
      - eureka

  youtube-search:
    container_name: "youtube-search"
    image: trcklst/youtube-search:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8010
      SPRING_PROFILE: docker
    ports:
      - "8010:8010"
    depends_on:
      - eureka

  zuul-server:
    container_name: "zuul-server"
    image: trcklst/zuul:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8888
      SPRING_PROFILE: docker
    ports:
      - "8888:8888"
    depends_on:
      - eureka

  user_db:
    container_name: "user_db"
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-volume/user:/data/db
    ports:
      - "27017:27017"

  subscription_db:
    container_name: "subscription_db"
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: subscription
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-volume/subscription:/data/db
    ports:
      - "27018:27018"
