### FORGET PASSWORD / send ###

POST http://localhost:8888/api/forget-password/send/
Content-Type: application/json

{
  "email": "decultot.louis@gmail.com"
}

### FORGET PASSWORD / reset ###

POST http://localhost:8888/api/forget-password/reset/
Content-Type: application/json

{
  "token": "1-Lk7IZu8mRAioIMScSrX0otnKocd2boQEzS5EJP36TrM86nQev31wcEK6z4EGoX1IoJLvNPqclhzfzHks1vY8ZAbRDgij5s4zwZKODoBjZH5WlYFq3RP53QFhb87txyuiq6GJEpwJnDJ1eD1Q3qJSiaqVlOps7nTpQl1QeZaVwmzifMcNKXkIrVBN7LMivICbCbLvyRIW",
  "newPassword": "lala"
}

###
PATCH http://localhost:8888/api/password/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkZWN1bHRvdC5sb3Vpc0BnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTQ2NzU0NzAsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6ImZjMDU0YWM5LWZkZGQtNDZmYS05Yjg3LTRkOWJiYTNmYTdhYiIsImVtYWlsIjoiZGVjdWx0b3QubG91aXNAZ21haWwuY29tIiwiY2xpZW50X2lkIjoidHJja2xzdCJ9.8sXB-cfCE0TmKAPWMF4dKszJhvNsyeYptFvzV6z0D_0

{
   "newPassword": "lala"
}



#############################################################################
#############################################################################
################ YOUTUBE SEARCH #############################################

POST http://localhost:8888/api/youtube/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkZWN1bHRvdC5sb3Vpc0BnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTQ0NTYxNzMsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6ImEwZTQ5NzQ1LWY0ZDQtNDA5OS1hZWY1LTA2Yjc4NWMxN2I5NSIsImVtYWlsIjoiZGVjdWx0b3QubG91aXNAZ21haWwuY29tIiwiY2xpZW50X2lkIjoidHJja2xzdCJ9.YhshZxAWkraQI1g3qfY81Is_q1TYfXgSGCt_Ip0uMJQ

{
   "query": "l",
   "itemsNumber": "10"
}

#############################################################################
#############################################################################
################ REGISTER ###################################################

POST http://localhost:8888/api/register
Content-Type: application/json

{
  "username": "decultot.louis@gmail.com",
  "password": "user"
}

#############################################################################
#############################################################################
################ AUTH #######################################################

POST http://localhost:8888/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic trcklst secret

password=user&username=decultot.louis@gmail.com&grant_type=password

###
POST http://localhost:8888/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTEwMDQ3MTMsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjIzODMzY2I1LTczZTEtNDc4Yy04ZjI5LTkxYzMzMzBkZjdiOSIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.22Fb5H-MFZi4QL8VhlcelKDODuO0tx_nRVcj_FGh0jc
Content-Type: application/json

#############################################################################
#############################################################################
################ SUBSCRIPTION ###############################################

GET http://localhost:8888/api/subscription/billing/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkZWN1bHRvdC5sb3Vpc0BnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTQ1MDMyNDMsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6Ijc5MjkwN2RiLTk4MWYtNDllMS1iMTY0LWQ3Mzk1YTZlMzdlYyIsImVtYWlsIjoiZGVjdWx0b3QubG91aXNAZ21haWwuY29tIiwiY2xpZW50X2lkIjoidHJja2xzdCJ9.xELgvxnD8ZERDlOyk6FsEPZUVcN2EesPGtmoTLlmW1A

###
POST http://localhost:8888/api/subscription/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkZWN1bHRvdC5sb3Vpc0BnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTQ1MDMyNDMsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6Ijc5MjkwN2RiLTk4MWYtNDllMS1iMTY0LWQ3Mzk1YTZlMzdlYyIsImVtYWlsIjoiZGVjdWx0b3QubG91aXNAZ21haWwuY29tIiwiY2xpZW50X2lkIjoidHJja2xzdCJ9.xELgvxnD8ZERDlOyk6FsEPZUVcN2EesPGtmoTLlmW1A

{
  "creditCard": {
    "number": "4242424242424242",
    "expirationMonth": 2,
    "expirationYear": 2023,
    "cvc": "837"
  },
  "subscriptionType": "PRO"
}

#############################################################################
#############################################################################
################ TRACK STREAM ###############################################

GET http://localhost:8888/stream/5edd4d1952cb0100a31f1a3b/0ThZIgyAnJQ
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTI0NjY2ODIsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6ImI4ZmNiOGQzLWE3ZjctNDNjZS1iNzkzLWE5OWQwNmVjOTJkMiIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.XczJ-kxkt37uCL7nDl8Q5sn2vv6m6CtlAZ9zgmv4DJQ

#############################################################################
#############################################################################
################ TRACK UPLOAD ###############################################

POST http://localhost:8888/upload/Gl9GtO_vQxw
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTI0NjY2ODIsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6ImI4ZmNiOGQzLWE3ZjctNDNjZS1iNzkzLWE5OWQwNmVjOTJkMiIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.XczJ-kxkt37uCL7nDl8Q5sn2vv6m6CtlAZ9zgmv4DJQ

#############################################################################
#############################################################################
################ PARTY ######################################################

### Create
POST http://localhost:8888/party
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTI0Njc2MzAsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6ImY5YWIzMjZlLWVlNmYtNGJjYi1iMzMzLTA4N2NmNWNhZTkyMiIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.O1KLvaTUIGSyWw_i8PCeoMxsyQOwCXjuYpf4S8ZqoG8

{
  "name": "Birthday"
}

### GET
GET http://localhost:8888/party/5ee202b270ef5e004d73602e
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTI0NjY2ODIsInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6ImI4ZmNiOGQzLWE3ZjctNDNjZS1iNzkzLWE5OWQwNmVjOTJkMiIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.XczJ-kxkt37uCL7nDl8Q5sn2vv6m6CtlAZ9zgmv4DJQ

### GET
GET http://localhost:8030/party/5eee86bb7bfdb90027d98dc1/search/oob
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3Vic2NyaXB0aW9uIjpudWxsfQ.f9AE2Tu14mJnz0m7KNhXU03ZsTxvFl_St-ztjJhqED4

### Delete
DELETE http://localhost:8888/party/5ee5051ce5dc0a008488c8fe
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M


### Edit
PUT http://localhost:8888/party/5ee54f11138d47002f10b52f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M

{
  "name": "QSDQSD"
}

### Join
PATCH http://localhost:8888/party/5ee54f11138d47002f10b52f/join
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M

### leave
PATCH http://localhost:8888/party/5ee54f11138d47002f10b52f/leave
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M

### add track
POST http://localhost:8888/party/5ee54f11138d47002f10b52f/add-track
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M

{
  "id": "i-o50WHxjj0",
  "name": "Booba - Cavaliero",
  "imageUrl": "http://img.jpg"
}

### Vote
PATCH http://localhost:8888/party/5ee54f11138d47002f10b52f/vote-track/w0BPaY6_9hs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyMkBnbWFpbC5jb20iLCJzY29wZSI6WyJhbGwiXSwic3Vic2NyaXB0aW9uIjpudWxsLCJleHAiOjE1OTI2MjkzMDksInVzZXJJZCI6MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjEwOWEyYTRmLTllM2UtNGFjOC05ZGZmLWJlNDUwY2FhNzgzMCIsImNsaWVudF9pZCI6InRyY2tsc3QifQ.2ltI7d20t5adrWxEtFOLKnY9sHlhAgKpDAVWL7RpRTw

### Unvote
PATCH http://localhost:8888/party/5eee86bb7bfdb90027d98dc1/unvote-track/i-o50WHxjj0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3Vic2NyaXB0aW9uIjpudWxsfQ.2wg6PnE78C9PavPkqU_BFCc45nGUCumU9aIm7jvUfoY


### Next-track
PUT http://localhost:8888/party/5ee54f11138d47002f10b52f/next-track
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M

### Pause
PATCH http://localhost:8888/party/5ee54f11138d47002f10b52f/pause
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M

### Play
PATCH http://localhost:8888/party/5ee54f11138d47002f10b52f/play
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Njk2OSwicm9sZSI6MX0.bB7OfYgkR4Nkpzt-Al2B2CXPomKlrk1uyeVTN-2iM6M
